name: Auto merge pull request

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "Pull Request Node CI"

jobs:
  merge:
    name: Auto Merge

    runs-on: ubuntu-latest

    steps:
      - name: Merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MAJOR
